export const REQUEST_GET_MORE_ACTIVE_VENALINK_LIST = 'REQUEST_GET_MORE_ACTIVE_VENALINK_LIST';
export const SUCCESS_GET_MORE_ACTIVE_VENALINK_LIST = 'SUCCESS_GET_MORE_ACTIVE_VENALINK_LIST';
export const FAILURE_GET_MORE_ACTIVE_VENALINK_LIST = 'FAILURE_GET_MORE_ACTIVE_VENALINK_LIST';

export const REQUEST_GET_MORE_SHARE_VENALINK_LIST = 'REQUEST_GET_MORE_SHARE_VENALINK_LIST';
export const SUCCESS_GET_MORE_SHARE_VENALINK_LIST = 'SUCCESS_GET_MORE_SHARE_VENALINK_LIST';
export const FAILURE_GET_MORE_SHARE_VENALINK_LIST = 'FAILURE_GET_MORE_SHARE_VENALINK_LIST';

export function requestGetMoreActiveVenalinkList(payload) {
  return {
    type: REQUEST_GET_MORE_ACTIVE_VENALINK_LIST,
    payload,
  };
}

export function requestGetMoreShareVenalinkList(payload) {
  return {
    type: REQUEST_GET_MORE_SHARE_VENALINK_LIST,
    payload,
  };
}
